# 系统整体版本信息
# System Version Information

# 系统总版本号
string system_version

# 配置版本号
int32 config_version

# 产品ID (如: 2.0, 1.1)
string product_id

# 产品描述
string product_description

# OEM厂商 (cmcc/ysc/unitree)
string oem

# 产品名称 (xiaoli)
string product_name

# 操作系统 (ubuntu2004)
string os

# CPU架构 (x86_64/aarch64)
string arch

# 所有组件版本信息
ComponentVersion[] components

# 系统构建时间戳
int64 system_build_timestamp

