#ifndef __ROS1_SRC_HOMI_SPEECH_INTERFACE_INCLUDE_HOMI_SPEECH_INTERFACE_DEF_H_
#define __ROS1_SRC_HOMI_SPEECH_INTERFACE_INCLUDE_HOMI_SPEECH_INTERFACE_DEF_H_

//以下宏不要使用
#define HOMI_AUDIO_PLAYER_PLAYFILE_SERVICE ""
namespace homi_speech_interface
{

    
}


#endif  // __ROS1_SRC_HOMI_SPEECH_INTERFACE_INCLUDE_HOMI_SPEECH_INTERFACE_DEF_H_
